"""initial models: weather_observations and beedar_readings

Revision ID: 9a7776c7a11f
Revises:
Create Date: 2026-06-25 13:59:58.369282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a7776c7a11f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beedar_readings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('hive_id', sa.Uuid(), nullable=True),
    sa.Column('radar_activity', sa.Float(), nullable=True),
    sa.Column('vibration_level', sa.Float(), nullable=True),
    sa.Column('battery_percent', sa.Float(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_index(op.f('ix_beedar_readings_device_id'), 'beedar_readings', ['device_id'], unique=False)
    op.create_index('ix_beedar_readings_device_time', 'beedar_readings', ['device_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_beedar_readings_hive_id'), 'beedar_readings', ['hive_id'], unique=False)
    op.create_index(op.f('ix_beedar_readings_timestamp'), 'beedar_readings', ['timestamp'], unique=False)
    op.create_table('weather_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('precipitation_inches', sa.Float(), nullable=True),
    sa.Column('relative_humidity', sa.Float(), nullable=True),
    sa.Column('cloud_cover', sa.Float(), nullable=True),
    sa.Column('wind_speed_mph', sa.Float(), nullable=True),
    sa.Column('surface_pressure_mb', sa.Float(), nullable=True),
    sa.Column('wind_direction_degrees', sa.Float(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_index(op.f('ix_weather_observations_timestamp'), 'weather_observations', ['timestamp'], unique=False)
    # ### end Alembic commands ###
    # === TimescaleDB Hypertables ===
    op.execute("""
        SELECT create_hypertable(
            'weather_observations',
            'timestamp',
            chunk_time_interval => INTERVAL '7 days',
            if_not_exists => TRUE
        );
    """)

    op.execute("""
        SELECT create_hypertable(
            'beedar_readings',
            'timestamp',
            chunk_time_interval => INTERVAL '7 days',
            if_not_exists => TRUE
        );
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_observations_timestamp'), table_name='weather_observations')
    op.drop_table('weather_observations')
    op.drop_index(op.f('ix_beedar_readings_timestamp'), table_name='beedar_readings')
    op.drop_index(op.f('ix_beedar_readings_hive_id'), table_name='beedar_readings')
    op.drop_index('ix_beedar_readings_device_time', table_name='beedar_readings')
    op.drop_index(op.f('ix_beedar_readings_device_id'), table_name='beedar_readings')
    op.drop_table('beedar_readings')
    # ### end Alembic commands ###
